GarageMVC/GarageMVC/Models/GarageViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GarageMVC.Models
{
	public class Garage
	{
		[Key]
		public int Id { get; set; }
		public int Spots { get; set; }
		public int OccupiedSpots { get; set; }
		public ParkedVehicleModel? Car { get; set; }
		[ForeignKey("CarId")]
		public int? CarId { get; set; }
	}
}

GarageMVC/GarageMVC/Controllers/GarageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GarageMVC.Data;
using GarageMVC.Models;
using GarageMVC.ViewModels;
using NuGet.Packaging.Signing;
using Humanizer;

namespace GarageMVC.Controllers
{
    public class GarageController : Controller
    {
        private readonly IGarageContext _context;
        private readonly VehicleConstants _constants;

        public GarageController(IGarageContext context, IConfiguration configuration)
        {
            _context = context;
            _constants = new VehicleConstants(configuration);
                //(configuration);     // For use with /Garage/Create
        }

        // GET: Garage
        public async Task<IActionResult> Index(string? situationSpecificMessage = null)
        {
            IEnumerable<VehicleOverviewViewModel> vehicleOverviews = await _context.ParkedVehicles.Select(pv => new VehicleOverviewViewModel(pv)).ToListAsync();

            int parkedVehiclesCount = vehicleOverviews.Count();
            int placesRemaining = ParkedVehicleModel.maxSpotNumber - parkedVehiclesCount;

            List<int> parkingSpotList =  vehicleOverviews.Select(pv => pv.ParkingSpotNumber).ToList();
            


            return View(new OverviewPageViewModel() { PlacesRemaining = placesRemaining, VehicleOverviews = vehicleOverviews, SituationSpecificMessage = situationSpecificMessage });
        }

        // GET: Garage/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var parkedVehicleModel = await _context.ParkedVehicles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (parkedVehicleModel == null)
            {
                return NotFound();
            }

            return View(parkedVehicleModel);
        }

        // GET: Garage/Create
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.VehicleConstants = _constants;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ParkedVehicleModel vehicle)
        {
            if (_context.ParkedVehicles.Any(v => v.RegistrationNumber == vehicle.RegistrationNumber))
            {
                ModelState.AddModelError("RegistrationNumber", "Registration number must be unique");
            }

            if (_context.ParkedVehicles.Any(v => v.ParkingSpotNumber == vehicle.ParkingSpotNumber))
            {
                ModelState.AddModelError("ParkingSpotNumber", "Spot number is occupied. Please choose another one.");
                return View(vehicle);
            }


            if (ModelState.IsValid)
            {
                // vehicle.TimeStamp = DateTime.Now;
                _context.ParkedVehicles.Add(vehicle);
                _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.VehicleConstants = _constants;
            return View(vehicle);
        }

        // Used for client side validation in conjunction with Remote attribute on ParkedVehicleModel
        [HttpGet]
        public async Task<IActionResult> CheckRegistration(string registrationNumber)
        {
            if (await _context.ParkedVehicles.AnyAsync(v => v.RegistrationNumber == registrationNumber))
            {
                return Json($"{registrationNumber} has already been taken.");
            }
            
            return Json(true);
        }



        // Get: Garage/Overview
        [HttpGet]
        public async Task<IActionResult> Overview()
        {
            var vehicles = await _context.ParkedVehicles.ToListAsync();
            var sumOfPrice = Math.Round(vehicles.Select(v => v.TotalCost).Sum(), 2);

            var model = new GarageOverviewViewModel
            {
                VehicleTypes = vehicles.Select(v => v.Type).Distinct().Select(s => " " + s).ToList(),
                VehicleColors = vehicles.Select(v => v.Color).Distinct().Select(s => " " + s).ToList(),
                VehicleBrands = vehicles.Select(v => v.Brand).Distinct().Select(s => " " + s).ToList(),
                SumOfAllWheels = vehicles.Select(v => v.NumberOfWheels).Sum(),
                SumOfPrice = sumOfPrice

            };

            return View(model);
        }



        // GET: Garage/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var parkedVehicleModel = await _context.ParkedVehicles.FindAsync(id);
            if (parkedVehicleModel == null)
            {
                return NotFound();
            }
            return View(parkedVehicleModel);
        }

        // POST: Garage/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Type,Color,RegistrationNumber,Brand,Model,NumberOfWheels, ParkingSpotNumber")] ParkedVehicleModel parkedVehicleModel)
        {
            if (id != parkedVehicleModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(parkedVehicleModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ParkedVehicleModelExists(parkedVehicleModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(parkedVehicleModel);
        }

        // GET: Garage/CheckOut/5
        public async Task<IActionResult> CheckOut(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var parkedVehicleModel = await _context.ParkedVehicles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (parkedVehicleModel == null)
            {
                return NotFound();
            }

            // Getting current time to calculate tot time
            DateTime currentTime = DateTime.Now;

            TimeSpan ParkedDuration = currentTime.Subtract(parkedVehicleModel.TimeStamp);
            // string cost = "";
            double totalCost = 0;
            totalCost = parkedVehicleModel.TotalCost;

            int hours = (int)ParkedDuration.TotalHours;
            int minutes = ParkedDuration.Minutes;
            string parkedTime = string.Format("{0:00} hours & {1:00} minutes", hours, minutes);
            string parkedAt = $"{parkedVehicleModel.TimeStamp:yyyy-MM-dd HH:mm}";

            // if parked less than an hour
            // then count as one hour
            if (hours < 1)
            {
                totalCost = ParkedVehicleModel.pricePerHour;
            }
            // if parked more than an hour
            else if ( hours >= 1)
            {
                // if minutes are less than 30
                // count it as half an hour extra
                if (minutes < 30)
                {
                    double roundHour = hours + 0.5;
                    totalCost = Math.Round((ParkedVehicleModel.pricePerHour * roundHour), 2);
                }
                // else count it as one hour extra
                else if (minutes >= 30)
                {
                    int roundHour = hours + 1;
                    totalCost = Math.Round((ParkedVehicleModel.pricePerHour * roundHour), 2);
                }
            }

            parkedVehicleModel.ParkedDuration = parkedTime;
            parkedVehicleModel.TotalCost = totalCost;
            parkedVehicleModel.parkedAt = parkedAt;
            return View(parkedVehicleModel);
        }

        // POST: Garage/CheckOut/5
        [HttpPost, ActionName("CheckOut")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var parkedVehicleModel = await _context.ParkedVehicles.FindAsync(id);
            if (parkedVehicleModel != null)
            {
                _context.ParkedVehicles.Remove(parkedVehicleModel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> SearchByRegistrationNumber(string registrationNumber)
        {
            ParkedVehicleModel? searchResult = await _context.ParkedVehicles.FirstOrDefaultAsync(v => v.RegistrationNumber == registrationNumber);
            if (searchResult == null)
                return RedirectToAction(nameof(Index), new { situationSpecificMessage = "The registration number was not found." });
            return RedirectToAction(nameof(Details), new { id = searchResult.Id });
        }


        private bool ParkedVehicleModelExists(int id)
        {
            return _context.ParkedVehicles.Any(e => e.Id == id);
        }
    }
}

GarageMVC/GarageMVC/Views/Garage/CheckOut.cshtml
@model GarageMVC.Models.ParkedVehicleModel

@{
    ViewData["Title"] = "CheckOut";
}

<div class="jumbotron">
    <h1>Check Out</h1>
    <p>Are you sure you want to Check Out now?</p>
</div>
<hr />
<div class="p-3 mb-2 bg-dark text-white">
    
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.parkedAt)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.parkedAt)
        </dd>
    </dl>

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
    </dl>

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
    </dl>

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RegistrationNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RegistrationNumber)
        </dd>
    </dl>

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Brand)
        </dd>
    </dl>

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Model)
        </dd>
    </dl>

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfWheels)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NumberOfWheels)
        </dd>
    </dl>

     <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ParkedDuration)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ParkedDuration)
        </dd>
    </dl>

     <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ParkingSpotNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ParkingSpotNumber)
        </dd>
    </dl>

     <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TotalCost)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TotalCost) SEK
        </dd>
    </dl>

    </dl>

    <form asp-action="CheckOut">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Check Out" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

GarageMVC/GarageMVC/Views/Garage/Create.cshtml
@model GarageMVC.Models.ParkedVehicleModel

@{
    ViewData["Title"] = "Create";
    var vehicleConstants = ViewBag.VehicleConstants as GarageMVC.Data.VehicleConstants;
    var types = vehicleConstants?["Types"];
    var colors = vehicleConstants?["Colors"];

    if (ViewBag.RegistrationNumbers is not null)
    {
        var regNums = (IEnumerable<string>)ViewBag.RegistrationNumbers;
    }
    <!-- Use 'types' and 'colors' in your select elements -->
}

<div class="jumbotron">
    <h1>Create</h1>
    <p>Park a Vehicle</p>
</div>
<hr />

<div class="p-3 mb-2 bg-dark text-white">
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                
                <select asp-for="Type" class="form-control">
                    @if (types is not null)
                    {
                        @foreach(var type in types)
                        {
                            <option value="@type">@type</option>
                        }
                    }
                    '</select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <select asp-for="Color" class="form-control">
                    @if (colors is not null)
                    {
                        @foreach(var color in colors)
                        {
                            <option value="@color">@color</option>
                        }
                    }
                </select>
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="RegistrationNumber" class="control-label"></label>
                <input asp-for="RegistrationNumber" class="form-control" />
                <span asp-validation-for="RegistrationNumber" id="registration-error" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="NumberOfWheels" class="control-label"></label>
                <input asp-for="NumberOfWheels" class="form-control" />
                <span asp-validation-for="NumberOfWheels" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="ParkingSpotNumber" class="control-label"></label>
                <input asp-for="ParkingSpotNumber" class="form-control" />
                <span asp-validation-for="ParkingSpotNumber" id="registration-error" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Create</button>
            </div>
        </form>
    </div>
</div>
<br />
<div>
    <a asp-action="Index">Back to List</a>
</div>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

GarageMVC/GarageMVC/Views/Garage/Details.cshtml
@model GarageMVC.Models.ParkedVehicleModel

@{
    ViewData["Title"] = "Details";
}



<div class=" jumbotron">
    <h1>Details</h1>
    <p>Details of parked vehicle</p>

</div>
    <hr />

<div class="p-3 mb-2 bg-dark text-white">
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
    </dl>

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
    </dl>

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RegistrationNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RegistrationNumber)
        </dd>
    </dl>

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Brand)
        </dd>
    </dl>

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Model)
        </dd>
    </dl>

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfWheels)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NumberOfWheels)
        </dd>
    </dl>

<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a> |
    <a asp-action="CheckOut" asp-route-id="@Model?.Id">Check Out</a>
</div>
</div>

GarageMVC/GarageMVC/Views/Garage/Edit.cshtml
@model GarageMVC.Models.ParkedVehicleModel

@{
    ViewData["Title"] = "Edit";
}

<div class="jumbotron">

    <h1>Edit</h1>

    <p>Edit choosen vehicle</p>
</div>

<hr />

<div class="p-3 mb-2 bg-dark text-white">
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <label asp-for="Type" class="control-label"></label>
                    <input asp-for="Type" class="form-control" />
                    <span asp-validation-for="Type" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <label asp-for="Color" class="control-label"></label>
                    <input asp-for="Color" class="form-control" />
                    <span asp-validation-for="Color" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <label asp-for="RegistrationNumber" class="control-label"></label>
                    <input asp-for="RegistrationNumber" class="form-control" />
                    <span asp-validation-for="RegistrationNumber" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <label asp-for="Brand" class="control-label"></label>
                    <input asp-for="Brand" class="form-control" />
                    <span asp-validation-for="Brand" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <label asp-for="Model" class="control-label"></label>
                    <input asp-for="Model" class="form-control" />
                    <span asp-validation-for="Model" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <label asp-for="NumberOfWheels" class="control-label"></label>
                    <input asp-for="NumberOfWheels" class="form-control" />
                    <span asp-validation-for="NumberOfWheels" class="text-danger"></span>
                </div>
                <br />
                @Html.HiddenFor(Model => Model.ParkingSpotNumber)
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
                <br />
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

GarageMVC/GarageMVC/Views/Garage/Index.cshtml
@using GarageMVC.ViewModels
@model OverviewPageViewModel
@{
    ViewData["Title"] = "Index";
}


<div>
    <div class="jumbotron">
        <h1>Welcome</h1>
        <p>To the GarageMVC parking</p>
        <p>
            <a asp-controller="Garage" asp-action="Create">Park a vehicle</a>
        </p>

        <p>
            <a asp-controller="Garage" asp-action="Overview">Garage Overview</a>
        </p>
    </div>
    @if(!String.IsNullOrEmpty(Model.SituationSpecificMessage))
    {
        <p>
            @Model.SituationSpecificMessage
        </p>
    }
  
   <p>
        There are @Model.PlacesRemaining spots remaining.
    </p>

    <div class="row mb-4">
        @if (Model.VehicleOverviews != null)
        {
            for (int i = 1; i <= 30; i++) // Iterate from 1 to 30
            {
                string spotStatus = Model.VehicleOverviews.Any(pv => pv.ParkingSpotNumber == i) ? "occupied" : i.ToString();

                <span class="col-sm-2"> @spotStatus</span>
            }
        }
    </div>


    <div class="table-responsive">
    <form asp-controller="Garage" asp-action="SearchByRegistrationNumber">
        <label>Registration number</label>
        <input name="registrationNumber" />
        <button type="submit" class="btn btn-primary">Search</button>
    </form>
    </div>
    <div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.VehicleOverviews.First().Type)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.VehicleOverviews.First().RegistrationNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.VehicleOverviews.First().TimeStamp)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.VehicleOverviews.First().ParkingSpotNumber)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.VehicleOverviews)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Type)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RegistrationNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TimeStamp)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ParkingSpotNumber)
                    </td>
                    <td>
                    <td>
                        <a asp-controller= "Garage" asp-action="Details" asp-route-id="@item.Id">Details</a>
                    </td>
                </tr>
            }             
        </tbody>
    </table>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</div>

GarageMVC/GarageMVC/Views/Garage/Overview.cshtml
@model GarageMVC.ViewModels.GarageOverviewViewModel

@{
    ViewData["Title"] = "Overview";
}



<div class="jumbotron">
    <h1>Garage Overview</h1>
    <p>Currently parked vehicles</p>
</div>
<hr />

<div class="p-3 mb-2 bg-dark text-white">
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.VehicleTypes)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.VehicleTypes)
        </dd>
    </dl>

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.VehicleBrands)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.VehicleBrands)
        </dd>
    </dl>

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.VehicleColors)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.VehicleColors)
        </dd>
    </dl>

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SumOfAllWheels)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SumOfAllWheels)
        </dd>
    </dl>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SumOfPrice)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SumOfPrice)
            
        </dd>
    </dl>


    <div>

        <a asp-action="Index">Back to List</a>
    </div>
</div>